baseURL = 'https://ieee-unm.github.io/IEEE-UNM-website/about/' #https://IEEEUNMSB.com/
languageCode = 'en-us'
title = 'IEEE UNM SB'
theme = ["timer-hugo"]
# post pagination
paginate = "3" # see https://gohugo.io/extras/pagination/
summaryLength = 20 

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Events"
url = "events/"
weight = 3

[[menu.main]]
name = "Spark Initiative"
url = "spark-initiative/"
weight = 4

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# Site Params
[params]
home = "Home"
logo = "images/Final Logo small.png"
dateFormat = "2 January 2006, Monday"
# Meta data
description = "IEEE UNM SB Website"
author = "IEEE UNM SB"

# Banner Section
[params.banner]
enable = true
bgImage = "images/bg1.jpg"
heading = "IEEE UNM Student Branch"
description = "Technological Innovation and Excellence for the Benefit of Humanity."
# button
btn = true
btnText = "MORE ABOUT US"
btnURL = "about/"

# flip text on hero banner
[[params.banner.flipText]]
title = "Electrical"
[[params.banner.flipText]]
title = "Electronic"
[[params.banner.flipText]]
title = "Mechatronic"
[[params.banner.flipText]]
title = "Computer Science"



# Homepage Vision & Mission Section
[params.about]
enable = true
title = "Vision & Mission"
#content = 
background_image = "images/IEEE Logo Only.svg"
image = "images/Final Logo.png"

[[params.about.item]]
icon  = "ion-ios-eye"
title = "Vision"
description = "To create a rapport community that fosters great teamwork and inspires lifelong-learning in the field of Electrical and Electronic Engineering. "

[[params.about.item]]
icon  = "ion-android-locate"
title = "Mission"
description = "IEEE UNM SB organises participant-centered events and activities that will benefit the participants in their professional and personal development."


# Past Events Section On Homepage
[params.portfolio]
enable = true
title = "Past Events"


# Call to Action before footer 
[params.cta]
enable = true
title = "Contact Us"
#content = "Please"
btnText = "Contact us"
btnURL = "contact/"


# footer social icon
[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/ieee_unm/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/ieee-unm-student-branch/?originalSubdomain=my"

[permalinks]
tags = "/tag/:slug/"