baseURL = 'https://IEEEUNMSB.com/'
languageCode = 'en-us'
title = 'IEEE UNM SB'
theme = ["timer-hugo"]
# post pagination
paginate = "3" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Events"
url = "events/"
weight = 3

[[menu.main]]
name = "Spark Initiative"
url = "spark-initiative/"
weight = 4

[[menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# Site Params
[params]
home = "Home"
logo = "images/Final Logo small.png"
dateFormat = "2 January 2006, Monday"
# Meta data
description = "IEEE UNM SB Website"
author = "IEEE UNM SB"
# Google Analitycs
# googleAnalitycsID = "Your ID"
# contact form action
# contactFormAction = "#" # contact form works with https://formspree.io


# Banner Section
[params.banner]
enable = true
bgImage = "images/bg1.jpg"
heading = "IEEE UNM Student Branch"
description = "Technological Innovation and Excellence for the Benefit of Humanity."
# button
btn = true
btnText = "MORE ABOUT US"
btnURL = "about/"

# flip text on hero banner
[[params.banner.flipText]]
title = "Electrical"
[[params.banner.flipText]]
title = "Electronic"
[[params.banner.flipText]]
title = "Mechatronic"
[[params.banner.flipText]]
title = "Computer Science"

# Homepage About/Hero Section
[params.about]
enable = true
title = "Vision & Mission"
#content = 
background_image = "images/IEEE Logo Only.svg"
image = "images/Final Logo.png"

# Call to Action before footer 
[params.cta]
enable = true
title = "CONTACT US"
#content = "Please"
btnText = "Contact us"
btnURL = "contact/"

# Past Events Section On Homepage
[params.portfolio]
enable = true
title = "Past Events"
parent_dir = ["2022-2023","2023-2024"]

# footer social icon
[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/ieee_unm/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/ieee-unm-student-branch/?originalSubdomain=my"