# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "IEEE Website"
license = "MIT"
licenselink = "https://github.com/IEEE-UNM/IEEE-UNM-hugo-theme/blob/master/LICENSE"
description = "Hugo theme for IEEE UNM website"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[params]
  mainSections = ["events", "spark-initiative"]

[author]
  name = "IEEE UNM"
  homepage = "IEEE UNM"
